export const BasicFunctions = [
    { id: 0, name: '椒盐噪声' },
    { id: 1, name: '均值平滑' },
    { id: 2, name: '中值平滑' },
    { id: 3, name: '高斯平滑' },
    { id: 4, name: '图像锐化-拉普拉斯算子' },
    { id: 5, name: '图像锐化-Sobel算子水平方向' },
    { id: 6, name: '图像锐化-Sobel算子垂直方向' },
    { id: 7, name: '将图像用双线性插值法扩大图像' },
    { id: 8, name: '左移30个像素，下移50个像素' },
    { id: 9, name: '旋转45度，缩放因子为1' },
    { id: 10, name: '转灰度图' },
    { id: 11, name: '转灰度后二值化-全局阈值法' },
    { id: 12, name: '直方图均衡化' },
    { id: 13, name: '灰度直方图' },
    { id: 14, name: '仿射变换' },
    { id: 15, name: '透视变换' },
    { id: 16, name: '图像翻转' },
    { id: 17, name: 'rgb转hsv' },
    { id: 18, name: 'hsv获取h' },
    { id: 19, name: 'hsv获取s' },
    { id: 20, name: 'hsv获取v' },
    { id: 21, name: 'rgb获取b' },
    { id: 22, name: 'rgb获取g' },
    { id: 23, name: 'rgb获取r' },
    { id: 24, name: '水平翻转' },
    { id: 25, name: '垂直翻转' },
    { id: 26, name: '对角镜像' },
    { id: 27, name: '图像开运算' },
    { id: 28, name: '图像闭运算' },
    { id: 29, name: '腐蚀' },
    { id: 30, name: '膨胀' },
    { id: 31, name: '顶帽运算' },
    { id: 32, name: '底帽运算' },
    { id: 33, name: 'houghLinesP实现线条检测' },
    { id: 34, name: 'canny边缘检测' },
    { id: 35, name: '图像增强' },
    { id: 36, name: 'Roberts算子提取图像边缘' },
    { id: 37, name: 'Prewitt 算子提取图像边缘' },
    { id: 38, name: 'Laplacian算子提取图像边缘' },
    { id: 39, name: 'LoG边缘提取' },
];

export const StyleCategories = [
    { id: 40, name: '糖果风格', path: require("@/static/style-type/candy.jpg")},
    { id: 41, name: '星空风格', path: require("@/static/style-type/starry_night.jpg")},
    { id: 42, name: '毕加索风格', path: require("@/static/style-type/composition_vii.jpg")},
    { id: 43, name: '缪斯风格', path: require("@/static/style-type/la_muse.jpg")},
    { id: 44, name: '马赛克风格', path: require("@/static/style-type/mosaic.jpg")},
    { id: 45, name: '神奈川冲浪里风格', path: require("@/static/style-type/wave_crop.jpg")},
    { id: 46, name: '达达主义风格', path: require("@/static/style-type/udnie.jpg")},
    { id: 47, name: '呐喊风格', path: require("@/static/style-type/the_scream.jpg")},
    { id: 48, name: '羽毛风格', path: require("@/static/style-type/feathers.jpg")},
]
